pipeline:
  web:
    image: microsoft/dotnet:2.0.0-sdk-2.0.2-jessie
    commands:
      - dotnet restore
      - dotnet build
    when:
      branch: master
      event: [ push ]
  notify:
    image: drillster/drone-email
    host: ${email_host}
    username: ${email_username}
    password: ${email_password}
    from: ${email_address}
    recipients: [ $email_recipients ]